# Generated by Django 3.1.1 on 2020-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadds',
            name='phone',
            field=models.CharField(max_length=150),
        ),
    ]
