# Generated by Django 3.1.1 on 2020-09-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_jobadds_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobadds',
            old_name='since_date',
            new_name='user_since',
        ),
    ]
