# Generated by Django 3.1.1 on 2020-10-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_auto_20201004_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadds',
            name='heading',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobadds',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobadds',
            name='price',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobadds',
            name='user_since',
            field=models.CharField(max_length=150),
        ),
    ]
