# Generated by Django 3.1.1 on 2020-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_auto_20201004_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadds',
            name='link',
            field=models.SlugField(max_length=255),
        ),
    ]
