# Generated by Django 3.1.1 on 2020-09-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_auto_20200917_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadds',
            name='link',
            field=models.SlugField(),
        ),
    ]
