# Generated by Django 3.1.1 on 2020-10-03 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0004_auto_20200917_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadds',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 13, 38, 25, 121900, tzinfo=utc)),
        ),
    ]
