# Generated by Django 3.1.1 on 2020-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0005_jobadds_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadds',
            name='time',
            field=models.CharField(default='10-03', max_length=20),
        ),
    ]
