# Generated by Django 3.1.1 on 2020-10-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0006_auto_20201003_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadds',
            name='time',
            field=models.CharField(default='10/03/2020', max_length=20),
        ),
    ]
